### PR TITLE
Park and ride

### PR DESCRIPTION
**Pull request by leonardehrenfried**
As the graph and the RoutingRequest classes are mutable, this is still a little buggy and/or racy.

I'm going to have to figure out how to create a proper clone of the request and run in parallel with the park and ride one.

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
I tried a few variations of the above code and couldn't get it to work reliably.

I'm beginning to suspect that it's the parallelism that is creating the unclean state.

Do you have an idea, @hbruch ?

**Comment by hbruch** [comment]
What are the issues you encounter? Not sure if that is the issue you encounter, but I think that the exception handling needs to take into account, that either of both requests could time out or not find a path while the other would. In that case, we should return the result of the successful query.

**Comment by leonardehrenfried** [comment]
The problems I see are the following:

- The first hand full of requests work as expected.
- After perhaps the second or third request I start seeing the following errors in the log:

```
09:50:28.238 WARN (GraphPathFinder.java:533) About to add null lastState to newPath. This may cause nullPointer in next iteration? Caused by traversing edge: TemporaryPartialStreetEdge(road, <osm:node:5177635601 lat,lng=48.701210100000004,9.0037578> -> <split from 1479943 lat,lng=48.70069199004047,9.003353452963163> length=64.804 carSpeed=11.11112 parentEdge=StreetWithElevationEdge(1479943, road, <osm:node:5177635601 lat,lng=48.701210100000004,9.0037578> -> <osm:node:5177635589 lat,lng=48.699603800000006,9.0025042> length=200.913 carSpeed=11.11112 permission=ALL))
09:50:28.239 WARN (GraphPathFinder.java:185) CompactLegsByReversedSearch failed on request: 48.612710848943586,8.842620849609375 48.70047813100718,9.003982543945312 804.672 Mon Nov 04 09:49:00 CET 2019 false QUICK WALK,TRAM,SUBWAY,RAIL,BUS,FERRY,CABLE_CAR,GONDOLA,FUNICULAR,TRANSIT,AIRPLANE 3
09:50:28.607 WARN (GraphPathFinder.java:533) About to add null lastState to newPath. This may cause nullPointer in next iteration? Caused by traversing edge: TemporaryPartialStreetEdge(road, <osm:node:5177635589 lat,lng=48.699603800000006,9.0025042> -> <split from 1479942 lat,lng=48.70069199004047,9.003353452963163> length=136.109 carSpeed=11.11112 parentEdge=StreetWithElevationEdge(1479942, road, <osm:node:5177635589 lat,lng=48.699603800000006,9.0025042> -> <osm:node:5177635601 lat,lng=48.701210100000004,9.0037578> length=200.913 carSpeed=11.11112 permission=ALL))
09:50:28.607 WARN (GraphPathFinder.java:185) CompactLegsByReversedSearch failed on request: 48.612710848943586,8.842620849609375 48.70047813100718,9.003982543945312 804.672 Mon Nov 04 09:49:00 CET 2019 false QUICK WALK,TRAM,SUBWAY,RAIL,BUS,FERRY,CABLE_CAR,GONDOLA,FUNICULAR,TRANSIT,AIRPLANE 3
```
- From there on the functionality degrades and only car trips are returned, even for routes which should have a P+R option.
- If you move the start and end points away from the previous routes, you might be able to get another trip with a P+R option (but that is also not reliably reproduced).
- After a few dozen requests you will get a `RouteNotFoundException`, but again, this cannot be reliably reproduced.

**Comment by leonardehrenfried** [comment]
I went down this rabbit hole tonight and I think I've managed to shed a little bit of light onto this.

Sooooo, the warnings are actually not meaningful in this context. I swapped back to the original code and they still appear. Therefore I ignored them. (This alone took a while to figure out.)

This also means that it was probably not the parallelism that was causing the problems either.

This has left me with one area of investigation: the filtering logic. And indeed there I found something: I was checking if an `Edge` is a of class `StreetEdge`. However, what I should have done is to check if it can is of this type _and all of its subclasses_, like `StreetEdgeWithElevationData`! This also explains why it work in the previous week (before I had added the elevation data to my graph).

What I have done now, so as to not put the feature delivery in jeopardy, is to leave the code in a definitely working state, even though it's probably overly cautious:

- no parallelism
- the routing request is cloned _very_ defensively (I thought that could be the culprit - it wasn't)

What is still not watertight is the error handling in case that a path could not be found. I'm going to have to leave that for another day.

**Comment by leonardehrenfried** [comment]
The magic ingredient: https://github.com/mfdz/OpenTripPlanner/pull/1/commits/8fc4f5cc5aa52b9b6473da0b194fbc4adf70c56d#diff-de7c92a94309073e41616649c7065faaR51

**Pull request merged**
