### PR TITLE
VehicleParking opening hours and updaters

### PR DESCRIPTION
**Pull request by flaktack**
This is a combination of thre branches, and adds support for
 * vehicle parking opening hours () and updaters (#48)
 * filtering by tag / network for parking and bicycle rental (#59)

`router-config.json` updater configuration:
```
    {
      "type": "vehicle-parking",
      "sourceType": "park-api",
      "frequencySec": 30,
      "feedId": "PAPI",
      "url": "https://api.stadtnavi.de/herrenberg/parking/parkapi.json"
    },
    {
      "type": "vehicle-parking",
      "sourceType": "open-bike-box",
      "frequencySec": 30,
      "feedId": "OBB",
      "url": "https://backend.openbikebox.next-site.de/api/v1/locations?format=list"
    }
```

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Nice work.

One Question: what is the feedId for? In other updaters that references a GTFS feed.

**Comment by flaktack** [comment]
That is for creating the IDs for the VehicleParking places, so that different updaters may reuse the existing ID.

**Comment by flaktack** [comment]
There is also a ParkAPI source for OpenBikeBox: https://backend.openbikebox.next-site.de/api/park-api/1.0 and https://backend.openbikebox.next-site.de/api/park-api/1.0/1

**Comment by leonardehrenfried** [comment]
So I tried this out but routing requests with CAR_PARK fail with a 500 for me:

http://localhost:8080/otp/routers/default/plan?fromPlace=48.61180289568751%2C8.840818405151367&toPlace=48.59386747325061%2C8.867254257202148&time=2%3A39pm&date=06-03-2021&mode=CAR_PARK%2CTRANSIT&maxWalkDistance=4828.032&arriveBy=false&wheelchair=false&debugItineraryFilter=false&locale=en

Weirdly there is nothing in the logs that would indicate what the problem is.

**Comment by leonardehrenfried** [comment]
Does it work for you?

**Comment by leonardehrenfried** [comment]
The same thing happens when I use the GraphQL API.

**Comment by flaktack** [comment]
I'm looking into it -- I've only run the tests after the latest set of merges.

**Comment by flaktack** [comment]
The request seems to fail due to a `StackOverflowError`, I'm still looking into the actual reason.
```
java.lang.StackOverflowError
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at io.leonard.OpeningHoursEvaluator.timeMatchesDayRanges(OpeningHoursEvaluator.java:126)
	at io.leonard.OpeningHoursEvaluator.timeMatchesRule(OpeningHoursEvaluator.java:120)
	at io.leonard.OpeningHoursEvaluator.lambda$isOpenAt$1(OpeningHoursEvaluator.java:37)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at io.leonard.OpeningHoursEvaluator.isOpenAt(OpeningHoursEvaluator.java:37)
	at io.leonard.OpeningHoursEvaluator.isOpenIterative(OpeningHoursEvaluator.java:50)
	at io.leonard.OpeningHoursEvaluator.isOpenIterative(OpeningHoursEvaluator.java:91)
	at io.leonard.OpeningHoursEvaluator.isOpenIterative(OpeningHoursEvaluator.java:91)
        ...
```

**Comment by flaktack** [comment]
`OpeningHoursEvaluator` needed a few changes, after which requests worked again for me:
https://github.com/leonardehrenfried/opening-hours-evaluator/pull/2

**Comment by leonardehrenfried** [comment]
Hmm, there is a strange compilation error on CI which I cannot reproduce locally.

**Comment by leonardehrenfried** [comment]
My gut feeling is that it's to do with the jar files so I would try removing the restore key from the CI step, so that they are downloaded again.

**Comment by flaktack** [comment]
It fails for me locally, but I haven't figured out what the cause is. It seems to be related to the `1.1.0` version if `opening-hours-evaluator`. Adding an explicit dependency on `OpeningHoursParser` fixes it:
```
        <dependency>
            <groupId>ch.poole</groupId>
            <artifactId>OpeningHoursParser</artifactId>
            <version>0.23.2</version>
        </dependency>
```

**Comment by leonardehrenfried** [comment]
If I look at the POM i see scope=runtime which doesn't look right: https://repo.maven.apache.org/maven2/io/leonard/opening-hours-evaluator/1.1.0/opening-hours-evaluator-1.1.0.pom

Although I would expect a different error.

**Comment by leonardehrenfried** [comment]
I'm currently publishing another artifact which uses the comile scope instead.

**Comment by leonardehrenfried** [comment]
I've released another version 1.2.1 with the compile scope: https://repo.maven.apache.org/maven2/io/leonard/opening-hours-evaluator/1.2.1/opening-hours-evaluator-1.2.1.pom

**Comment by leonardehrenfried** [comment]
In case you're wondering what the problem was: https://github.com/leonardehrenfried/opening-hours-evaluator/commit/f1594eb1c33036bbdf44b31496626130cfaa7e84

I'm beginning to hate gradle just as much as maven.

**Comment by flaktack** [comment]
:1st_place_medal: thanks for getting it to work, I've updated the used dependency.

**Comment by leonardehrenfried** [comment]
Screenshot_20210605-065425

Does exactly what it is supposed to do.

**Pull request merged**
